import type { Metadata } from "next";
import localFont from "next/font/local";
import '../app/globals.css';

// Add these two imports
import NavBar from './components/NavBar/NavBar';
import Footer from './components/Footer/Footer';

const geistSans = localFont({
  src: "../app/public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../app/public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavBar />
        <div className="container">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}